### ISSUE TITLE
Sync blog and forum posts

### ISSUE THREAD

**Issue by rtabbara** [MRtrix3/MRtrix3.github.io#4]
From ISMRM meeting: Ideally we want the ability to push content from a forum post to a blog post (or vice versa) and additionally have the corresponding forum comments displayed inline on the website.

**Comment by rtabbara** [comment]
Ok, I've now setup the ability to link inline comments of an existing forum post to a particular blog post. Check out 

http://www.mrtrix.org/2016/05/05/image-registration-and-fixel-based-analysis/

as an example. In particular, in the preamble markdown of your post, you can now specify the (optional) corresponding discourse id: e.g.

```
---
layout: post
title: Image registration and fixel-based analysis
author: draffelt
date: 2016-05-05 16:16:00 -0600
categories:
discourse_id: 207 <--- new thing
---
```

The id is given by the forum post link. e.g.

http://community.mrtrix.org/t/image-registration-and-fixel-based-analysis-now-available-in-mrtrix/207

For new content, in terms of automatically pushing a blog post to the forum, that might be a bit problematic because from what I can see, currently Discourse only allows a single user to have that ability. That is, right now any blog post that we push will automatically be assumed to be created by @jdtournier even if the blog post was created by another user. So if we wanted multiple users to have this ability, we would probably have to roll something ourselves.

Probably the simplest thing would be to  invert the problem, so that a user would first write and publish the forum post and then we could have a local script that would scrape that content and then generate the corresponding markdown blog post. A user would still have to subsequently manually push this post on git, but as a plus, this would give them the flexibility of modifying the content in the instance that they don't want the forum and blog posts to be perfectly aligned.

**Comment by jdtournier** [comment]
Check out the [`blog_from_discourse` branch on the MRtrix3.github.io](https://github.com/MRtrix3/MRtrix3.github.io/tree/blog_from_discourse?files=1) - in particular the [`gen_ blog` script](https://github.com/MRtrix3/MRtrix3.github.io/blob/blog_from_discourse/gen_blog.py). I had a go at precisely that last idea a couple of weeks ago... (pulling from Discourse into the website). Just needs a trigger, which I couldn't figure out - at least nothing more complicated than a simple timer-based approach. I'd rather not need to push manually to trigger this, part of the appeal is not needing to do the whole git clone/commit/push dance to add a blog post - and make use of Discourse's editing and preview features. I was hoping there would be a simple way to trigger some machine to run this script and push the results to the website, but I can't think of anything simple...

I don't anticipate needing the blog posts to ever be different on the website and Discourse. What might be trickier would be to show comments on the website...? But then we could always just add a link to the discourse topic, with a label like 'discuss this post' or 'join the discussion' or something like that... Might be a nice way to bring people into the forum too.

**Comment by rtabbara** [comment]
Thanks @jdtournier! I've polished up the script and merged. I've also updated the README [here](https://github.com/MRtrix3/MRtrix3.github.io/blob/blog_from_discourse/README.md#for-content-contributors--writing-posts-using-content-from-community-forum) with relevant instructions.

Hopefully, if all goes well, we should also have inline forum comments at the bottom of the blog posts too. 

I'll close this off for now, but if anyone encounters any issues/suggestions, please let me know.

**Comment by rtabbara** [comment]
@jdtournier Ah, just reread your last comment and realise you were after a fully-automated solution. Probably a bit too keen to close this off :smile: I'll take a look around to see if something like this is possible.

One problem I immediately see which I've mentioned in the README, is that the author entry will be pre-filled with the Discourse handle, whereas we need this to coincide with the GitHub handle in order to fetch the author's profile pic/links etc. But we could certainly refactor this to make the Discourse handle the primary key for fetching author details, so it's not a deal-breaker.

**Comment by thijsdhollander** [comment]
> But we could certainly refactor this to make the Discourse handle the primary key for fetching author details, so it's not a deal-breaker.

This actually makes much more sense, compared to the github handle.  Our most visible profile on the MRtrix _website_ is the Discourse profile after all.  That is, in the end, how we interact with the MRtrix _community_.  The github one is just a necessary construct for development, but barely represents a public profile at all.  It'd be nice to just change any current links to the github "profile" to the Discourse one.

**Comment by jdtournier** [comment]
Good stuff Rami! Just to recap, what we currently have is a system that allows posts to be fetched from the Discourse Announcements category, but by default only the latest topic will be fetched. The correspondence between Github & Discourse handles is sorted with your latest commit, so that's no longer an issue. Comments are enabled for these posts, and to contribute, users are taken directly to the relevant topic on the community forum - which is perfect. So any comments made on the community topic will show up on the blog too. 

This sounds great, just a few things I'd like to discuss before we consider this ready for prime time:
- I'd like the update of the blog on the website to be fully automatic. I'm just not sure how to achieve that... The simplest is to simply run the script every 10 minutes or something, but that might prove a bit too heavy in the long run. Particularly since I think the script should update _all_ posts (more on that later). Another option is to set up a simple system that allows us to push a bogus commit on the website, just enough to change the SHA1 of the master branch, which can be picked up by a script set to run every ~5 minutes or so. Checking the SHA1 for updates is trivial, and the full blog update script would only be triggered if there has been an update. So maybe we could just instruct users to [add a bogus file via the GitHub interface](https://github.com/MRtrix3/MRtrix3.github.io/new/master) (named something like `trigger`), which the update script would subsequently remove - that would add two commits to the history for every blog post, but provide a simple interface to trigger an update without too much effort. I reckon that would be pretty simple to use for blog contributors.
- I think the script should update _all_ posts. Reason being that you might want to update a post for typos, etc. and that post might not be the most recent. I'm actually not too fussed about that, I can see that the chances are any corrections for typos are likely to happen very quickly after the original post, and so the chances are it will still be the most recent at that time. And there is an option to run the script for all posts anyway. But if we use the above strategy, there's no reason not to run the script for all posts, it would be a relatively infrequent operation.
- Is the Announcements category the right category? Should we have a Blog category? Better still, should we have both categories, and scrub posts from both sources...?
- I think we should remove the original posts from the website and update the corresponding community topics with their full content. That way subsequent updates will pull them in as-is. Thankfully, I'm pretty sure all blog posts also have corresponding Announcements topics, so we can simply edit these posts in place without notifying everyone, and preserve the original author and timestamp. At that point, we'd just need to run the blog update script, and these posts would be pulled in from Discourse without much fuss... 

Thoughts?

**Comment by rtabbara** [comment]
> So maybe we could just instruct users to add a bogus file via the GitHub interface (named something like trigger)
- I think if you're after a trigger for when a new discourse announcement occurs, what about a cron job on the DO server that just performs a json request similar to `gen_blog.py` that just checks the timestamp of the latest post?

> I think the script should update all posts. 
- Yep, originally when I was thinking of a manual setup, the idea was that a user would post on the forum and then immediately run the script. But I agree for a fully-automated solution we should (potentially) be updating a larger number of posts.

My initial feeling was to have a daily cron job that would run, check if new forum posts are available and then subsequently generate the corresponding blog posts. I thought that 24 hours would be more than enough time for users to fix up any missing info/typos within their posts and that a one day delay for the blog/forum to sync up isn't a huge inconvenience.

Moreover, if there is a necessity to re-generate all posts for whatever reason, a user can still manually call `gen_blog.py --all`

> Is the Announcements category the right category? Should we have a Blog category?

Yes, I would be in favour of a separate Blog category, simply because not all Announcements (such as a scheduled maintenance) warrant a blog post.

> I think we should remove the original posts from the website and update the corresponding community topics with their full content

Given the above, I'm a bit reluctant then to retrospectively modify the existing Announcements. Older forum posts also have click counts to the corresponding blog post links, which might also be something we want to maintain.

**Comment by jdtournier** [comment]
> what about a cron job on the DO server that just performs a json request similar to gen_blog.py that just checks the timestamp of the latest post?

That's what I had in mind initially, but it won't trigger an update when someone edits an older post. I'd rather have a solution that works regardless. 

> I thought that 24 hours would be more than enough time for users to fix up any missing info/typos within their posts and that a one day delay for the blog/forum to sync up isn't a huge inconvenience.

That might actually be the most sensible approach. Posting on the community means the blog is out straight away and those people who monitor the forum will get notified. Maybe it's no big deal if it takes a few hours to get updated on the website... In which case we could just run a cron job and set it to run through all the posts regardless, which would guarantee everything is kept in sync.

> Yes, I would be in favour of a separate Blog category, simply because not all Announcements (such as a scheduled maintenance) warrant a blog post.

True... But I'm actually not too bothered about an announcement of that nature making its way into the blog on the website - if anything, it shows that the site is alive and active. I'd be happy with that. In many ways, more blog posts is better than no blog posts, even if some of them may not be all that relevant to your average visitor... 

> Older forum posts also have click counts to the corresponding blog post links, which might also be something we want to maintain.

I just had a look at the click counts - the highest is currently 25... Not something I think we need to get too excited about - at least not at this stage, it's still early days. I'd still rather edit the relevant current announcements and have them regenerated as posts by the script, it just seems like the simplest way to set things up moving forwards: that's how blog posts get generated on the website, end of story...

**Comment by rtabbara** [comment]
OK, sounds good. Just to recap for those who want the executive summary. We're proposing:
- Port old blog post content to the discourse forum announcements. Hopefully, this is easy enough without changing authorship/timestamps.
- Add a daily cron task on our digital ocean server that currently hosts our forum. Will clone the MRtrix website git repo and subsequently run a script to generate blog posts for _all_ forum announcements. Any diffs will be committed and pushed.
- In particular, this means in the future, any forum announcements will automatically sync-up with the website (after at most a day) to have a corresponding blog post.

If there's no other suggestions/objections from other people, I'll take a look at this tomorrow.

**Comment by draffelt** [comment]
All sounds sensible to me.

**Comment by thijsdhollander** [comment]
> Just to recap for those who want the executive summary.

I should've started reading from the bottom... that's a very handy summary. :smile: 
It all sounds very sensible to me too, I very much love the syncing between the forum announcements and corresponding blog posts. :+1:

**Comment by draffelt** [comment]
Fortunately I came across the executive summary first. We need more of those on Github!

**Comment by rtabbara** [comment]
This has now been setup. I've tested running the script manually for the initial scrape and it seems to be working fine. I've also subsequently made a minor change to an old post and will wait and see if by tomorrow the cron job picks up the changes.

**Comment by jdtournier** [comment]
Nice work! Quick question: do images show up OK? I'm guessing they'll pulling in the existing images from Discourse rather than copying them over to the Jekyll site...?

**Comment by rtabbara** [comment]
I've now updated the `gen_blog` script to pull the raw markdown of the post  rather than the cooked html. In particular, there was an issue with how images were being displayed that should now be fixed.

@jdtournier Yes, currently the blog is referencing images from Discourse. After the switch to raw markdown, I had to slightly modify the script to handle local image references. Do you think that's ok or do you think that we should also upload the images over to the website?

**Comment by jdtournier** [comment]
Happy for the images to remain on Discourse, no need to duplicate. Just something to bear in mind if we ever change the domain name...

As to pulling the raw markdown: the reason I'd gone for the cooked html was that it was less likely to be affected by differences in the markdown flavour used by Discourse vs. Jekyll. But it seems to render fine at the moment (assuming the stuff currently live on the MRtrix blog is already pulled from Discourse?), so let's worry about that it/when there's a problem...
